#Expyriment 1.0.0 (Python 3.13.7), .xpe-file, coding: cp1252
#date: Wed Oct 08 2025 17:25:27
#sha1: f2faa3
#modules: drawing_functions.py (ea2ea7)
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Windows', node='zlr778', release='11', version='10.0.22631', machine='AMD64')
Time,Type,Event,Value,Detail,Detail2
828,stderr,received,'Traceback (most recent call last):'
829,stderr,received,'  File "C:\\Users\\20946\\CogSup\\Programming\\Assignments\\Week-4\\Exercises\\Ternus_illusion.py", line 8, in <module>\n    from drawing_functions import load, timed_draw, present_for'
829,stderr,received,'  File "C:\\Users\\20946\\CogSup\\Programming\\Assignments\\Week-4\\Exercises\\drawing_functions.py", line 63, in <module>\n    present_for(stims, 500)\n    ~~~~~~~~~~~^^^^^^^^^^^^'
829,stderr,received,'  File "C:\\Users\\20946\\CogSup\\Programming\\Assignments\\Week-4\\Exercises\\drawing_functions.py", line 36, in present_for\n    dt = timed_draw(stims)'
829,stderr,received,'  File "C:\\Users\\20946\\CogSup\\Programming\\Assignments\\Week-4\\Exercises\\drawing_functions.py", line 19, in timed_draw\n    t0 = exp.clock.time()'
830,stderr,received,"TypeError: 'int' object is not callable"
